[package]
name = "fanfictionnet"
version = "0.1.0"
authors = ["François Monniot <francoismonniot@gmail.com>"]
edition = "2018"

[dependencies]
scraper = "0.12.0"
hyper = "0.13.9"
hyper-tls = "0.4"
log = "0.4"
ego-tree = "0.6"
